AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  helloworld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: >-
        org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler::handleRequest
      Runtime: java11
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::249770225596:role/service-role/hello-world-role-78yl4hc2'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Environment:
        Variables:
          spring_cloud_function_definition: welcome
